"""empty message

Revision ID: 8c7d69c1fdad
Revises: 4797ff24111a
Create Date: 2019-11-23 23:14:03.116824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7d69c1fdad'
down_revision = '4797ff24111a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    # ### end Alembic commands ###
